// CT5 Pride Volunteer Roles Configuration
// This file is automatically updated by the admin panel

export const roles = [
    {
        "id": "director-of-legal-and-compliance",
        "title": "Director of Legal & Compliance",
        "category": "governance",
        "department": "Board of Directors",
        "status": "open",
        "icon": "volunteers",
        "summary": "Join our Board of Directors as Director of Legal & Compliance, providing essential governance oversight and ensuring CT5 Pride operates within legal and regulatory frameworks.",
        "location": "CT5 Area (Whitstable, Seasalter, Tankerton, Chestfield, Swalecliffe, Yorkletts)",
        "reportingLine": "Board of Directors",
        "timeCommitment": "8-12 hours per month",
        "description": "<p>As Director of Legal & Compliance, you will play a crucial role in ensuring CT5 Pride operates with the highest standards of governance and legal compliance. This position is essential for maintaining our Community Interest Company status and building trust with our community and stakeholders.</p><p>You will work closely with the Board of Directors to develop and maintain robust governance frameworks, ensure compliance with relevant legislation, and provide strategic legal guidance to support our mission of serving the LGBTQIA+ community in the CT5 area.</p>",
        "essentialCriteria": [
            "Qualified solicitor or barrister with current practicing certificate, or equivalent legal qualification with relevant experience",
            "Minimum 5 years of post-qualification experience in corporate law, governance, or compliance",
            "Strong understanding of UK corporate law, particularly in relation to Community Interest Companies or similar structures",
            "Experience in governance frameworks, board operations, and regulatory compliance",
            "Excellent analytical and problem-solving skills, with the ability to provide clear, practical legal advice",
            "Strong commitment to equality, diversity, and inclusion, with a passion for supporting LGBTQIA+ communities",
            "Excellent communication skills, with the ability to explain complex legal concepts to non-legal stakeholders",
            "Proven experience in policy development and implementation",
            "Ability to work collaboratively with board members, staff, and external stakeholders",
            "High ethical standards and integrity in dealing with sensitive legal and governance matters"
        ],
        "desirableCriteria": [
            "Experience working with or advising non-profit organisations, charities, or community interest companies",
            "Knowledge of equality law and LGBTQIA+ rights legislation",
            "Experience in data protection and GDPR compliance",
            "Understanding of fundraising regulations and compliance requirements",
            "Experience in risk management and internal control frameworks",
            "Knowledge of employment law and HR compliance matters",
            "Experience working or volunteering within LGBTQIA+ organisations",
            "Familiarity with the CT5 area and local community networks",
            "Experience in developing and delivering training on legal and compliance matters",
            "Understanding of social media and digital communication compliance requirements"
        ]
    },
    {
        "id": "custom-director-of-administration-board-secretary",
        "title": "Director of Administration & Board Secretary",
        "category": "governance",
        "department": "Board of Directors",
        "status": "open",
        "icon": "volunteers",
        "summary": "The Director of Administration & Board Secretary ensures the smooth and compliant operation of CT5 Pride through effective administrative management and governance support. This includes coordinating board meetings, maintaining accurate records, managing internal communications, and upholding confidentiality. The role is central to the organisation’s structure and offers a potential pathway to senior leadership.",
        "location": "Kent, England",
        "reportingLine": "Senior Directors",
        "timeCommitment": "10-12 hours per month",
        "description": "The Director of Administration & Board Secretary (Officer) will be responsible for ensuring that CT5 Pride operates smoothly & efficiently through effective administration and governance. In this key leadership role, you will manage & oversee the administrative functions of the organisation, ensuring compliance with relevant laws and regulations. As the Board Secretary, you will facilitate the functioning of the Board of Directors by supporting governance processes, scheduling meetings, maintaining records, and ensuring proper communication between Board members and the wider organization. Your role will also involve managing sensitive & confidential information, acting as a key point of contact for Board members, and supporting organisational operations. Scope for this role to become a senior director in due course.\n\nWe are seeking a detail-oriented and highly organized individual with a strong understanding of governance and administrative functions in non-profit or community-based organizations. The ideal candidate will have experience in supporting boards and senior leadership teams, along with the ability to manage multiple administrative tasks simultaneously. You will be an excellent communicator, able to navigate complex situations and provide strategic administrative support to ensure CT5 Pride’s activities and operations are carried out effectively. Your commitment to maintaining transparency, confidentiality, and good governance will be key to your success in this role.",
        "essentialCriteria": [
            "- Applicants must be 18 years of age or over with no unspent convictions.",
            "- Be fluent in English written and spoken.",
            "- Not be barred from working with Children or vulnerable people.",
            "- A commitment to LGBTQIA+ inclusion and community-led values.",
            "- Willingness and ability undertake an active hands-on role.",
            "- Commitment to continuous learning and training.",
            "- Willingness to leverage professional and person networks to support fundraising and awareness efforts.",
            "- Proven experience (minimum 3 years) in an administrative role, with a focus on governance and supporting Board of Directors or senior leadership teams.",
            "- Policy & Procedure writing experience.",
            "- Strong understanding of governance structures, legal requirements, and board operations in the non-profit or community sector.",
            "- Experience in managing and maintaining accurate records, meeting minutes, and correspondence.",
            "- Excellent written and verbal communication skills, with experience preparing formal reports, minutes, and correspondence for Board members.",
            "- Ability to effectively communicate with Board members, staff, volunteers, and external stakeholders.",
            "- Strong commitment to confidentiality, with the ability to handle sensitive information with discretion and professionalism.",
            "- High ethical standards and integrity in dealing with governance and administrative matters."
        ],
        "desirableCriteria": [
            "- Previous experience serving as a company secretary, board officer, or in a governance or compliance role.",
            "- Understanding of the legal and regulatory framework for Community Interest Companies or charities.",
            "- Familiarity with filing requirements for Companies House or similar public bodies.",
            "- Experience supporting or developing policies, internal procedures, or organisational systems.",
            "- Knowledge of equality, diversity, and inclusion frameworks in practice.",
            "- Experience working or volunteering within LGBTQIA+ organisations or equalities-focused initiatives.",
            "- Strong written communication skills, with experience preparing formal documents or board papers.",
            "- Ability to manage shared drives or document storage systems such as Google Workspace or Microsoft 365.",
            "- Familiarity with coordinating AGMs, board recruitment, or director inductions.",
            "- A visible presence or active network within the CT5 area or broader Kent community.",
            "- Line-management experience in managing volunteers and/or staff."
        ]
    },
    {
        "id": "director-marketing-advertising",
        "title": "Director of Marketing and Advertising",
        "category": "marketing",
        "department": "Board of Directors",
        "status": "open",
        "icon": "social-media",
        "summary": "Lead CT5 Pride’s marketing strategy, shape public presence, manage campaigns, and guide a creative team to promote inclusion, diversity, and LGBTQIA+ visibility across all platforms.",
        "location": "CT5 Area, Kent",
        "reportingLine": "Senior Directors",
        "timeCommitment": "Adhoc, 8-10 hours per month may increase closer to Pride dates.",
        "description": "<p>The Director of Marketing and Advertising will play a critical role in shaping the public face of CT5 Pride. As the leader of the marketing team, you will be responsible for developing and executing marketing strategies that promote CT5 Pride’s mission, events, and campaigns. Working closely with the Senior Director, you will guide the public presence of CT5 Pride, helping to build awareness, engagement, and support within the community. You will lead the marketing team, including the Social Media Manager, and ensure that CT5 Pride’s voice is consistent, impactful, and inclusive across all platforms.</p>\n\n<p>We are looking for a creative and dynamic leader with a passion for marketing, advertising, and community outreach. The ideal candidate will have experience in leading marketing teams, managing digital campaigns, and representing an organization in public-facing activities. You should be an excellent communicator, both written and verbal, with the ability to inspire and motivate a team. Additionally, you should possess the skills to innovate and adapt to evolving marketing trends while remaining true to the values of CT5 Pride: inclusion, diversity, and LGBTQIA+ visibility. </p>",
        "essentialCriteria": [
            "Applicants must be 18 years of age or over with no unspent convictions.",
            "Be fluent in English written and spoken.",
            "Not be barred from working with Children or vulnerable people.",
            "A commitment to LGBTQIA+ inclusion and community-led values.",
            "Willingness and ability undertake an active hands-on role.",
            "Have a minimum of 2-years connect to the CT5 Area.",
            "A minimum of 5 years in marketing, advertising, or communications, with at least 2 years in a leadership role.",
            "Proven experience developing and executing digital marketing strategies and campaigns, including paid advertising.",
            "Strong leadership abilities with experience managing and mentoring a team.",
            "Proven ability to work cross-functionally with senior leadership and other departments to meet organisational goals.",
            "Expertise in social media marketing and content creation, including experience with Facebook, Instagram, Twitter, LinkedIn, etc.",
            "Proficiency with digital marketing tools (Google Analytics, Hootsuite, etc.) to track, analyse, and optimise campaign performance.",
            "Exceptional written and verbal communication skills, with experience writing for diverse audiences.",
            "Exceptional written and verbal communication skills, with experience writing for diverse audiences.",
            "Comfortable in a public-facing role, speaking at events or representing the organisation in media interviews.",
            "Strong creative skills and the ability to develop engaging content that resonates with the LGBTQIA+ community.",
            "Ability to think strategically and adapt marketing efforts to meet organisational needs.",
            "Excellent organisational and time-management skills, with the ability to manage multiple projects simultaneously and deliver results within deadlines.",
            "Basic graphic design skills or familiarity with design tools (Adobe Creative Suite, Canva, etc.) to create marketing materials."
        ],
        "desirableCriteria": [
            "Experience in non-profit marketing or working with community-centered organisations is a plus.",
            "Experience in promoting community events or large-scale initiatives, especially those in the LGBTQIA+ space.",
            "Experience in supporting fundraising efforts or working with development teams to create marketing strategies that support financial goals.",
            "Experience in writing, submitting and bidding for Grants."
        ]
    },
    {
        "id": "director-fundraising-sponsorship",
        "title": "Director of Fundraising & Sponsorship",
        "category": "fundraising",
        "department": "Board of Directors",
        "status": "open",
        "icon": "fundraising",
        "summary": "Drive CT5 Pride’s fundraising strategy, securing sponsorships, donations, and grants. Build key relationships to ensure financial sustainability while championing LGBTQIA+ inclusion and community impact.",
        "location": "CT5 Area, Kent",
        "reportingLine": "Senior Directors",
        "timeCommitment": "Adhoc  8-10 hours per month may increase closer to Pride dates.",
        "description": "<p>The Director of Fundraising & Sponsorship will lead the development and execution of CT5 Pride's fundraising strategy. This role is key in securing financial support through donations, corporate partnerships, grants, and events. You will build and maintain relationships with donors and sponsors, ensuring CT5 Pride has the resources needed to support its mission and activities.</p>\n\n<p>We are seeking an experienced, strategic, and results-driven fundraiser with a proven track record in securing sponsorships, donations, and grants. The ideal candidate will be a skilled relationship-builder, able to engage a diverse range of stakeholders and lead successful fundraising campaigns. A passion for LGBTQIA+ advocacy and a commitment to CT5 Pride’s values are essential.</p>",
        "essentialCriteria": [
            "Applicants must be 18 years of age or over with no unspent convictions.",
            "Be fluent in English written and spoken.",
            "Not be barred from working with Children or vulnerable people.",
            "A commitment to LGBTQIA+ inclusion and community-led values.",
            "Willingness and ability undertake an active hands-on role.",
            "Have a minimum of 2-years connect to the CT5 Area.",
            "Strong Confident & Sales oriented person,",
            "Minimum 5 years in fundraising, sponsorship, or a similar senior role, with a proven record of securing major donations, corporate sponsorships, and grants.",
            "Proven experience developing and executing fundraising strategies.",
            "Strong leadership skills, with experience managing teams and driving fundraising initiatives.",
            "Excellent at building and maintaining relationships with donors, sponsors, and partners.",
            "Strong project management abilities, with experience managing multiple campaigns and meeting fundraising targets.",
            "Proven ability to work cross-functionally with senior leadership and other departments to meet organisational goals.",
            "Proven ability to write compelling and successful grant applications, including detailed proposals and reports, and managing the full grant lifecycle.",
            "Experience in researching and identifying potential sponsors, and creating and presenting tailored sponsorship packages that align with organisational goals.",
            "Ability to work collaboratively with the Director of Marketing and Advertising to create content that supports fundraising campaigns, including promotional materials, sponsorship assets, and event collateral.",
            "Strong negotiation skills to secure favorable terms in sponsorship agreements, ensuring both the organization and sponsors achieve their objectives.",
            "Comfortable with networking and outreach, particularly via LinkedIn and other professional channels, to identify new sponsorship and partnership opportunities.",
            "Proficiency in using digital tools and platforms for fundraising (e.g., fundraising software, CRM systems, LinkedIn, etc.) and creating digital sponsorship content.",
            "Ability to develop innovative fundraising ideas and sponsorship proposals that stand out in a competitive market."
        ],
        "desirableCriteria": [
            "Experience in non-profit marketing or working with community-centered organisations is a plus.",
            "Experience in promoting community events or large-scale initiatives, especially those in the LGBTQIA+ space.",
            "Established network within the corporate, nonprofit, and philanthropic communities, particularly those interested in supporting LGBTQIA+ initiatives.",
            "Have professional experience in event and marketing sponsorship opportunities."
        ]
    },
    {
        "id": "director-retail-merchadise",
        "title": "Director of Retail & Merchandise",
        "category": "events",
        "department": "Events & Operations",
        "status": "draft",
        "icon": "volunteers",
        "summary": "Oversee CT5 Pride’s retail and merchandise, coordinating vendors, stalls, and sales. Work with fundraising and marketing teams to enhance visibility, engagement, and income at events.",
        "location": "Kent, England",
        "reportingLine": "Senior Directors incl; Chairperson & Founders.",
        "timeCommitment": "Adhoc, 8-10 hours per month may increase closer to Pride dates.",
        "description": "<p>The Retail & Merchandise Director will manage all aspects of retail and merchandise at CT5 Pride events. This includes overseeing stall bookings, merchandise sales, vendor coordination, and collaborating with the Director of Fundraising & Sponsorship and Director of Marketing & Advertising to maximise retail opportunities and drive engagement.</p>\n<p>We’re seeking an organized, strategic individual with experience in retail management and event coordination. The ideal candidate will have a proven track record in managing merchandise sales, overseeing vendor relations, and working cross-functionally to drive retail success at events.</p>",
        "essentialCriteria": [
            "Applicants must be 18 years of age or over with no unspent convictions.",
            "Be fluent in English written and spoken.",
            "Not be barred from working with Children or vulnerable people.",
            "A commitment to LGBTQIA+ inclusion and community-led values.",
            "Willingness and ability undertake an active hands-on role.",
            "Have a minimum of 2-years connect to the CT5 Area.",
            "Proven experience in coordinating and managing vendor relationships, including booking retail stalls, negotiating contracts, and ensuring compliance with event guidelines and policies.",
            "Experience in establishing relationships with buyers and sellers to build a retail space.",
            "Ability to work closely with cross-functional teams, particularly the Director of Fundraising & Sponsorship and Director of Marketing & Advertising, to integrate retail strategies with overall fundraising and marketing goals.",
            "Strong expertise in retail sales and merchandise management, including product selection, inventory tracking, and the development of pricing strategies.",
            "5+ years in retail management, merchandising, or event coordination.",
            "Proven experience managing vendors and retail stall operations at events.",
            "Strong design mindset to maximise product display value.",
            "Excellent communication skills, both written and verbal, for interacting with vendors, sponsors, and internal stakeholders.",
            "Creative mindset to incorporate new idea with colleague such as marketing to source new retail opportunities.",
            "Ability to track retail sales, evaluate performance, and provide data-driven insights and recommendations for future events.",
            "Experience preparing post-event reports, summarizing sales, vendor satisfaction, and overall retail operations performance.",
            "Experience of recruiting managing a team of Volunteers.",
            "Experience in managing stakeholder relationships for stall bookings.Comfortable collaborating with the Event Manager to identify and maximize retail opportunities within event programming.",
            "Experience managing the logistics of vendor setup, inventory management, and coordination during events.",
            "Experience managing online retail platforms, including integration with event sales and merchandising efforts.",
            "Ability to work with marketing or design teams to develop creative merchandising strategies, including branded products and visually compelling displays.",
            "Experience creating and managing budgets for retail and merchandise operations, ensuring cost-efficiency while meeting sales goals.",
            "Experience promoting retail opportunities via digital channels, social media, and event marketing materials to boost visibility and increase sales."
        ],
        "desirableCriteria": [
            "Previous experience working within the LGBTQIA+ community or in advocacy-related events, bringing an understanding of how to create inclusive and engaging retail experiences.",
            "Knowledge of managing product licenses, ensuring that all merchandise complies with legal and trademark regulations."
        ]
    },
    {
        "id": "social-media-manager",
        "title": "Social Media Manager",
        "category": "marketing",
        "department": "Marketing & Communications",
        "status": "open",
        "icon": "social-media",
        "summary": "Lead CT5 Pride’s social media strategy, manage content and a designer, grow community engagement, and ensure our values of inclusion, diversity, and LGBTQIA+ visibility shine online.",
        "location": "Kent, England or Remote",
        "reportingLine": "Director of Marketing and Advertising",
        "timeCommitment": "Adhoc 4-5 hours per month may increase closer to Pride dates.",
        "description": "<p>The Social Media Manager will lead CT5 Pride’s social media presence, developing and executing strategies to engage and grow our community online. You will line manage a Graphic Designer. Reporting to the Director of Marketing and Advertising, you'll create content, manage platforms, and foster interaction with followers, ensuring our mission of inclusion, diversity, and LGBTQIA+ visibility is at the forefront of everything we share.</p>\n<p>We seek a creative and strategic individual with strong social media expertise and line management capabilities. You should have a passion for the LGBTQIA+ community and be skilled in growing online engagement. The ideal candidate will have the ability to create compelling content and effectively communicate CT5 Pride’s mission across all platforms, while engaging with our audience authentically and inclusively.</p>",
        "essentialCriteria": [
            "Applicants must be 18 years of age or over with no unspent convictions.",
            "Be fluent in English written and spoken.",
            "Not be barred from working with Children or vulnerable people.",
            "A commitment to LGBTQIA+ inclusion and community-led values.",
            "Willingness and ability undertake an active hands-on role.",
            "Have a minimum of 2-years connect to the CT5 Area.",
            "Proficiency in managing Facebook, Instagram, Twitter, TikTok, etc., and using scheduling/analytics tools like Hootsuite or Buffer.",
            "Ability to create engaging, on-brand content (posts, videos, stories) that resonates with diverse audiences.",
            "Excellent writing and communication skills, able to engage the community effectively and professionally.",
            "Strong creative skills to develop fresh content ideas and campaigns.",
            "Have access to internet and computer.",
            "Understanding basics of SEO, paid ads, and digital marketing strategies.",
            "Willingness to attend CT5 Pride events to capture live content and represent the organisation online."
        ],
        "desirableCriteria": [
            "Prior experience managing social media for a charity, grassroots group, or community organisation.",
            "Familiarity with LGBTQIA+ advocacy, campaigns, or awareness events.",
            "Experience using Canva, Adobe Express, or similar tools for creating graphics and visual content.",
            "Basic video editing skills for producing short-form content (e.g., Reels, TikToks, Stories).",
            "Confidence in engaging with followers via comments, messages, and live streams in a professional and inclusive manner.",
            "Experience in using data insights to adjust content strategy and improve engagement.",
            "Understanding of safeguarding and ethical considerations when posting content involving volunteers or the public.",
            "Experience working collaboratively with teams, including marketing, events, and fundraising.",
            "An understanding of the local CT5 community, including its culture, demographics, and key LGBTQIA+ spaces or issues."
        ]
    }
];

// SVG Icons for different role types
export const roleIcons = {
    "parade": `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>`,
    "social-media": `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M18.92 5.01C18.72 4.42 18.16 4 17.5 4h-11c-.66 0-1.22.42-1.42 1.01L3 11v8c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-8l-2.08-5.99zM9 16H7v-2h2v2zm4 0h-2v-2h2v2zm4 0h-2v-2h2v2z"/></svg>`,
    "outreach": `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M16 4c0-1.11.89-2 2-2s2 .89 2 2-.89 2-2 2-2-.89-2-2zm4 18v-6h2.5l-2.54-7.63A1.84 1.84 0 0 0 18.2 7c-.8 0-1.54.5-1.85 1.26l-1.92 5.76c-.15.45.15.98.64.98.18 0 .35-.06.49-.16l2.44-1.68V22h2zm-7.5-10.5c.83 0 1.5-.67 1.5-1.5s-.67-1.5-1.5-1.5S11 9.17 11 10s.67 1.5 1.5 1.5zM5.5 6c1.11 0 2-.89 2-2s-.89-2-2-2-2 .89-2 2 .89 2 2 2zm2.5 16v-7H9.5l-1.32-3.96c-.26-.79-.98-1.29-1.85-1.29C5.76 9.75 5.2 10.42 5.2 11.2c0 .27.08.53.22.74L7 16h1v6h2z"/></svg>`,
    "volunteers": `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M16 13c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm-3 6.5c0-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5-.67 1.5-1.5 1.5-1.5-.67-1.5-1.5zM8 13c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm8 4c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm-8 0c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2z"/></svg>`,
    "fundraising": `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1.41 16.09V20h-2.67v-1.93c-1.71-.36-3.16-1.46-3.27-3.4h1.96c.1 1.05.82 1.87 2.65 1.87 1.96 0 2.4-.98 2.4-1.59 0-.83-.44-1.61-2.67-2.14-2.48-.6-4.18-1.62-4.18-3.67 0-1.72 1.39-2.84 3.11-3.21V4h2.67v1.95c1.86.45 2.79 1.86 2.85 3.39H14.3c-.05-1.11-.64-1.87-2.22-1.87-1.5 0-2.4.68-2.4 1.64 0 .84.65 1.39 2.67 1.91s4.18 1.39 4.18 3.91c-.01 1.83-1.38 2.83-3.12 3.16z"/></svg>`,
    "youth": `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg>`
}; 