backend:
  name: git-gateway
  branch: main # Branch to update

# When using the Netlify CMS locally
local_backend: true

# Media files will be stored in the repo under images/uploads
media_folder: "images/uploads"
public_folder: "/images/uploads"

# Content Collections
collections:
  - name: "volunteer_roles"
    label: "Volunteer Roles"
    folder: "data/roles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} - {{department}} ({{status}})"
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "Role title (e.g., 'Social Media Manager')"}
      - {label: "Summary", name: "summary", widget: "text", hint: "Brief description for the role listing"}
      - {label: "Job Description", name: "job_description", widget: "markdown", hint: "Full role description with responsibilities"}
      - {label: "Essential Criteria", name: "essential_criteria", widget: "list", hint: "List key requirements", allow_add: true}
      - {label: "Desirable Criteria", name: "desirable_criteria", widget: "list", hint: "List nice-to-have skills", allow_add: true}
      - {
          label: "Department",
          name: "department",
          widget: "select",
          options: ["Outreach", "Production", "Marketing", "Operations", "Admin"],
          hint: "Select the department this role belongs to"
        }
      - {label: "Application Deadline", name: "application_deadline", widget: "datetime", hint: "When applications close"}
      - {
          label: "Status",
          name: "status",
          widget: "select",
          options: ["Open", "Closed", "Paused"],
          hint: "Current status of this role"
        }
      - {label: "Apply Button Label", name: "apply_button_label", widget: "string", default: "Apply Now", hint: "Text shown on the apply button"}
      - {label: "Form Target ID", name: "form_target_id", widget: "string", hint: "Technical ID used to trigger the correct form popup"}
      - {
          label: "Role Image",
          name: "role_image",
          widget: "image",
          required: false,
          hint: "Optional image for this role (SVG, PNG, or JPG)",
          media_library: {
            max_file_size: 512000, # Limit to 500KB
            allowed_types: ["svg", "png", "jpg", "jpeg"]
          }
        }

  - name: "applications"
    label: "Applications"
    folder: "data/applications"
    create: true
    slug: "{{year}}{{month}}{{day}}-{{hour}}{{minute}}-{{slug}}"
    summary: "{{full_name}} - {{applied_role}} ({{submission_date}})"
    fields:
      - {label: "Full Name", name: "full_name", widget: "string"}
      - {label: "Email", name: "email", widget: "string", pattern: ['^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$', "Must be a valid email address"]}
      - {label: "Cover Letter", name: "cover_letter", widget: "text", hint: "Applicant's cover letter"}
      - {
          label: "CV Upload",
          name: "cv_upload",
          widget: "file",
          hint: "Applicant's CV (PDF or DOC)",
          media_library: {
            max_file_size: 5120000, # Limit to 5MB
            allowed_types: ["pdf", "doc", "docx"]
          }
        }
      - {
          label: "Applied Role",
          name: "applied_role",
          widget: "relation",
          collection: "volunteer_roles",
          search_fields: ["title"],
          value_field: "title",
          display_fields: ["title"],
          hint: "The role being applied for"
        }
      - {
          label: "Submission Date",
          name: "submission_date",
          widget: "datetime",
          default: "",
          format: "YYYY-MM-DD HH:mm:ss",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm:ss",
          hint: "Auto-generated submission timestamp"
        } 